version: "3.9"
services:
  mysql:
    image: mariadb:10.8.3
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: roots
    networks:
      - app-network
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    networks:
      - app-network
    ports:
      - 8085:8080

networks:
  app-network:
    driver: bridge
